version: "3.9"
x-database-credentials: &database-credentials
    DATABASE_USER: ${DATABASE_USER:-postgres}
    DATABASE_PASSWORD: ${DATABASE_PASSWORD:-password}
x-clickhouse-credentials: &clickhouse-credentials
    CLICKHOUSE_USER: ${CLICKHOUSE_USER:-dittofeed}
    CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD:-password}
x-backend-app-env: &backend-app-env
    <<: [*clickhouse-credentials, *database-credentials]
    NODE_ENV: production
    DATABASE_HOST: ${DATABASE_HOST:-postgres}
    DATABASE_PORT: ${DATABASE_PORT:-5432}
    CLICKHOUSE_HOST: ${CLICKHOUSE_HOST:-http://clickhouse-server:8123}
    TEMPORAL_ADDRESS: ${TEMPORAL_ADDRESS:-temporal:7233}
    WORKSPACE_NAME: ${WORKSPACE_NAME:-Default}
    AUTH_MODE: ${AUTH_MODE:-single-tenant}
    SECRET_KEY: ${SECRET_KEY:-GEGL1RHjFVOxIO80Dp8+ODlZPOjm2IDBJB/UunHlf3c=}
    PASSWORD: ${PASSWORD:-password}
    DASHBOARD_API_BASE: ${DASHBOARD_API_BASE:-http://localhost:3000}
services:
    lite:
      image: ${IMAGE_REPOSITORY:-dittofeed/dittofeed-lite}:${IMAGE_TAG:-v0.22.0}
      restart: always
      command: node --max-old-space-size=${LITE_MEM_LIMIT:-824} ./packages/lite/dist/scripts/startLite.js --workspace-name=${WORKSPACE_NAME:-Default}
      logging:
        driver: "local"
      deploy:
        resources:
          limits:
            memory: ${LITE_CONTAINER_MEM_LIMIT:-1024}m
      depends_on:
        - postgres
        - temporal
        - clickhouse-server
      environment:
        <<: *backend-app-env
        BOOTSTRAP: "true"
      env_file:
        - .env
      networks:
        - dittofeed-network-lite
    temporal:
      container_name: temporal
      restart: always
      logging:
        driver: "local"
      depends_on:
        - postgres
      environment:
        - DB=postgresql
        - DB_PORT=${DATABASE_PORT:-5432}
        - POSTGRES_USER=${DATABASE_USER:-postgres}
        - POSTGRES_PWD=${DATABASE_PASSWORD:-password}
        - POSTGRES_SEEDS=${DATABASE_HOST:-postgres}
        - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/docker.yaml
      env_file:
        - .env
      image: temporalio/auto-setup:${TEMPORAL_VERSION:-1.22.4}
      labels:
        kompose.volume.type: configMap
      networks:
        - dittofeed-network-lite
    postgres:
      image: postgres:${POSTGRES_VERSION:-15}
      restart: always
      logging:
        driver: "local"
      environment:
        - POSTGRES_PASSWORD=${DATABASE_PASSWORD:-password}
        - POSTGRES_USER=${DATABASE_USER:-postgres}
        - POSTGRES_DB=dittofeed
      volumes:
        - postgres:/var/lib/postgresql/data
      networks:
        - dittofeed-network-lite
    clickhouse-server:
      image: clickhouse/clickhouse-server:24.12.6.70-alpine
      restart: always
      logging:
        driver: "local"
      deploy:
        resources:
          limits:
            memory: ${CLICKHOUSE_CONTAINER_MEM_LIMIT:-2048}m
      environment:
        <<: *clickhouse-credentials
      volumes:
        - clickhouse_lib:/var/lib/clickhouse
        - clickhouse_log:/var/log/clickhouse-server
      networks:
        - dittofeed-network-lite
volumes:
    postgres:
    clickhouse_lib:
    clickhouse_log:
networks:
    dittofeed-network-lite:
      driver: bridge
      name: dittofeed-network-lite
